# Generated by Django 3.1.4 on 2022-05-25 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SIPRIData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_arms_sales', models.FileField(blank=True, null=True, upload_to='SIPRI_data/')),
                ('top_hundred_companies', models.FileField(blank=True, null=True, upload_to='SIPRI_data/')),
                ('date_uploaded', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
