# Generated by Django 3.1.4 on 2022-06-09 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application_frontend', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sipridata',
            options={'verbose_name_plural': 'SIPRI Datasets'},
        ),
    ]
