##############################################################
# The docker-compose file for testing the REST API
##############################################################

version: '3.9'
services:
  
  rest-api:
    build: ./
    container_name: rest-api
    env_file:
      - .env
    ports: 
      - "80:80"
    networks: 
      - rest_api_network

  
  rest-api-db:
    image: postgres:latest
    container_name: rest-api-db
    volumes: 
      - rest-api-psql-volume:/var/lib/postgresql/data
    env_file: 
      .env
    restart: always
    networks:
      - rest_api_network

networks: 
  rest_api_network:

volumes:
  rest-api-psql-volume: