##############################################################
# The main docker-compose file for standing up the mono-repo 
# of the data ingestion project.
##############################################################
---
version: '3.9'
services:

  # The Nginx Server for Routing Traffic:
  nginx:
    build: ./nginx
    networks: 
      - rest_api_network
    ports: 
      - "80:80" 

  # Django REST API:
  private-rest-api:
    tty: true
    build: private_rest_api/.
    depends_on: 
      - redis
      - rest-api-psql
    container_name: ETL-rest-api
    networks: 
      - rest_api_network
    env_file:
      .env

  # Reddis Database for Celery:
  redis:
    image: redis
    networks: 
      - rest_api_network
    command: redis-server 

  # PostgreSQL Database for the rest api:
  rest-api-psql:
    image: postgres
    container_name: rest-api-psql
    restart: always
    networks: 
      - rest_api_network
    volumes: 
      - rest-api-psql-volume:/var/lib/postgresql/data
    env_file: 
      .env

volumes:
  rest-api-psql-volume:

networks:
  rest_api_network:
    
