##############################################################
# The docker-compose file for testing the REST API
##############################################################

version: '3.9'
services:
  
  rest-api:
    build: ./
    container_name: rest-api
    env_file:
      - .env
    volumes: 
      - rest-api-db:/db.sqlite3
    ports: 
      - "80:80"

volumes:
  rest-api-db: