# Generated by Django 3.1.4 on 2022-02-15 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TwitterDeveloperAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(max_length=20)),
                ('api_key', models.CharField(max_length=25, unique=True)),
                ('api_secret_key', models.CharField(max_length=50, unique=True)),
                ('bearer_token', models.CharField(max_length=120, unique=True)),
                ('access_token', models.CharField(max_length=50, unique=True)),
                ('access_token_secret', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TwitterRegion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location_type', models.CharField(max_length=20)),
                ('parentid', models.IntegerField()),
                ('country', models.CharField(max_length=100)),
                ('woeid', models.IntegerField(unique=True)),
                ('country_code', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TrendingTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('promoted_content', models.BooleanField(blank=True, null=True)),
                ('topic_query', models.CharField(max_length=100)),
                ('tweet_volume', models.IntegerField()),
                ('created_at', models.DateTimeField()),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='twitter_api.twitterregion')),
            ],
        ),
    ]
