# Generated by Django 3.1.4 on 2022-02-15 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TrendingTopic',
            new_name='TrendingTwitterTopic',
        ),
        migrations.AlterField(
            model_name='twitterregion',
            name='country_code',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
