# Generated by Django 3.1.4 on 2022-03-25 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_api', '0002_auto_20220215_0725'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trendingtwittertopic',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='trendingtwittertopic',
            name='tweet_volume',
            field=models.IntegerField(null=True),
        ),
    ]
