# Generated by Django 3.1.4 on 2022-10-01 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PROFILE_API', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Profile Categories',
            },
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name_plural': 'Profiles'},
        ),
        migrations.RemoveField(
            model_name='profile',
            name='category',
        ),
        migrations.AddField(
            model_name='profile',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, to='PROFILE_API.ProfileCategory'),
        ),
    ]
