# Generated by Django 3.1.4 on 2022-10-02 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PROFILE_API', '0002_auto_20221001_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='category',
            field=models.ManyToManyField(blank=True, to='PROFILE_API.ProfileCategory'),
        ),
    ]
