# Generated by Django 3.1.4 on 2021-12-27 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RedditPosts',
            fields=[
                ('id', models.CharField(db_index=True, max_length=20, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300, null=True)),
                ('subreddit', models.CharField(max_length=200, null=True)),
                ('content', models.TextField(null=True)),
                ('upvote_ratio', models.FloatField(null=True)),
                ('score', models.IntegerField(null=True)),
                ('num_comments', models.IntegerField(null=True)),
                ('created_on', models.DateTimeField()),
                ('stickied', models.BooleanField(null=True)),
                ('over_18', models.BooleanField(null=True)),
                ('spoiler', models.BooleanField(null=True)),
                ('author_is_gold', models.BooleanField(null=True)),
                ('author_mod', models.BooleanField(null=True)),
                ('author_has_verified_email', models.BooleanField(null=True)),
                ('permalink', models.CharField(max_length=300, null=True)),
                ('author', models.CharField(max_length=300, null=True)),
                ('author_created', models.DateTimeField(null=True)),
                ('comment_karma', models.IntegerField(null=True)),
            ],
            options={
                'verbose_name_plural': 'Reddit Posts',
                'ordering': ['created_on'],
                'abstract': False,
            },
        ),
    ]
