# Generated by Django 3.1.4 on 2021-12-27 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reddit_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='redditposts',
            options={'ordering': ['-created_on'], 'verbose_name_plural': 'Reddit Posts'},
        ),
        migrations.AlterModelTable(
            name='redditposts',
            table='reddit_post_models',
        ),
    ]
