# Generated by Django 3.1.4 on 2021-12-27 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reddit_api', '0002_auto_20211227_0241'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='redditposts',
            table='redditposts',
        ),
    ]
