# Generated by Django 3.1.4 on 2022-05-25 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles_api', '0007_article_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='ceteris_paribus/articles/'),
        ),
    ]
