# Generated by Django 3.1.4 on 2022-06-09 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles_api', '0008_auto_20220525_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='img_source',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
