# Generated by Django 3.1.4 on 2022-10-02 01:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('PROFILE_API', '0003_auto_20221002_0125'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('created_on', models.DateTimeField(blank=True, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('authors', models.ManyToManyField(blank=True, to='PROFILE_API.Profile')),
                ('category', models.ManyToManyField(blank=True, to='PROFILE_API.ProfileCategory')),
                ('publisher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ARTICLE_API.publication')),
            ],
            options={
                'verbose_name_plural': 'News Articles',
            },
        ),
    ]
