name: Docker Image CI

on:
  push:
    branches: [ main ]

env:
  # PostgreSQL Configuration:
  POSTGRES_PORT: 5432 
  # Django Server Configuration: 
  PRODUCTION: True

jobs:

  build:

    runs-on: ubuntu-latest  
    environment: main_deployment  
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker Compose stack
      run: docker-compose up --build -d 
